account/urls.py
from tkinter.font import names

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    #path('login/', views.user_login, name='login')
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/<int:profile_id>/', views.different_user_profile, name='different_user_profile'),
    path('password-change/', views.my_PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password-reset/', views.my_PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.my_PasswordResetConfirmView.as_view(), name='password_reset_confirm' ),
    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('', views.dashboard, name='dashboard')

]

chat/urls.py
from django.urls import path, re_path
from . import views

# create urls

urlpatterns = [
    path('<int:ticket_id>/', views.chat_detail, name='chat_detail'),
    path('boss/<int:chat_id>', views.get_chat_boss, name='get_chat_boss'),
    path('send_message/<int:chat_id>/', views.send_message, name='send_message'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
    path("__reload__/", include("django_browser_reload.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

chat/models.py
from django.db import models

# Create your models here.
# chat/models.py

from django.db import models
from django.conf import settings
from tickets.models import Ticket  # импортируем тикет
from account.models import CustomUser

class Chat(models.Model):
    ticket = models.OneToOneField(
        Ticket,
        on_delete=models.CASCADE,
        related_name="chat"
    )
    participants = models.ManyToManyField(CustomUser)
    created_at = models.DateTimeField(auto_now_add=True)

    is_active = models.BooleanField(default=True)  # Добавляем флаг активности

    def __str__(self):
        return f"Chat for Ticket #{self.ticket.id}"

class ChatMessage(models.Model):
    chat = models.ForeignKey(
        Chat,
        on_delete=models.CASCADE,
        related_name="messages"
    )
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender.username} at {self.timestamp}"

chat/views.py
from django.shortcuts import render

# Create your views here.
# chat/views.py
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Chat, ChatMessage
from tickets.models import Ticket
from django.http import HttpResponseForbidden
from django.db.models import Q

@login_required
def send_message(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.method == "POST":
        message_text = request.POST.get("message")
        if message_text:
            ChatMessage.objects.create(
                chat=chat,
                sender=request.user,
                message=message_text
            )
    return redirect('chats:chat_detail', ticket_id=chat.ticket.id)
# chat/views.py


def chat_detail(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)

    has_access = request.user == ticket.created_by or request.user == ticket.accepted_by

    chat = get_object_or_404(Chat, ticket=ticket, is_active=True)
    # Проходимся по тикетам и ищем "другого" участника чата


    # Retrieve all messages for the chat (ordered by timestamp)
    messages = ChatMessage.objects.filter(chat=chat).order_by('timestamp')
    chats = Chat.objects.filter(
        Q(ticket__accepted_by=request.user) | Q(ticket__created_by=request.user), is_active=True
    )
    for ticket in chats:
        # Получаем чат
        other_user = ticket.participants.exclude(id=request.user.id).first()  # Исключаем текущего пользователя
        ticket.other_participant = other_user  # Добавляем в объект ticket

    return render(request, 'chat/chat_detail.html', {
        'ticket': ticket,
        'chat': chat,
        'messages': messages,  # pass messages to template
        'has_access': has_access,  # <-- передаем в шаблон
        'tickets': chats
    })

def get_chat_boss(request, chat_id):
    first_sender = None
    chat = get_object_or_404(Chat, id=chat_id)
    messages = ChatMessage.objects.filter(chat=chat).order_by('timestamp')
    if messages:
        first_sender = messages.first().sender
    if request.user == chat.ticket.department.boss:
        return render(request, 'chat/get_chat_boss.html', {
            'chat': chat,
            'messages': messages,
            'first_sender': first_sender
        })

    return HttpResponseForbidden("Доступ запрещен")

templates/chat/chat_detail.html
{% load static %}
{% load tailwind_tags %}

{% block content %}
<!--<div class="flex flex-col items-center justify-center min-h-screen bg-gray-100">-->


    {% if has_access %}
    <button type="button" onclick="closeChat()" class="absolute top-2 right-2 text-gray-500 hover:text-red-600 text-xl font-bold">&times;</button>
    <div class="w-full max-w-lg mb-4">
        <div class="flex space-x-2 overflow-x-auto p-2 bg-gray-50 rounded-lg">
        {% for t in tickets %}
        <div class="flex items-center space-x-2 bg-white border border-gray-300 rounded-lg shadow-sm p-2 hover:bg-gray-100 transition cursor-pointer"
             data-ticket-id="{{ t.ticket.id }}"
             onclick="loadChat({{ t.ticket.id }})">
            <div class="flex flex-col text-left">
                <span class="font-medium text-gray-800">Чат с {{ t.other_participant }}</span>
            </div>
            <a href="{% url 'account:different_user_profile' t.other_participant.id %}" class="btn btn-ghost p-1 hover:ring-2 hover:ring-primary rounded-full transition-all"
               onclick="event.stopPropagation();">
                {% if t.other_participant.profile.photo %}
                    <img src="{{ t.other_participant.profile.photo.url }}" alt="Profile Picture"
                         class="w-8 h-8 rounded-full border-2 border-primary object-cover pointer-events-none">
                {% else %}
                    <img src="/media/tickets/def.png" alt="Default Profile Picture"
                         class="w-8 h-8 rounded-full border-2 border-gray-200 object-cover pointer-events-none">
                {% endif %}
            </a>
        </div>
        {% endfor %}
    </div>


    </div>

        <h1 class="text-2xl font-bold text-center text-gray-800">Чат для задания #{{ chat.ticket.id }}</h1>
        <div class="chats-container overflow-y-auto h-80 p-4 border rounded-lg bg-gray-50" id="chats-container">
            {% for message in messages %}
                <div class="flex {% if message.sender == user %}justify-end{% else %}justify-start{% endif %}">
                    <div class="max-w-xs px-4 py-2 rounded-lg {% if message.sender == user %}bg-purple-600 text-white{% else %}bg-orange-500 text-white{% endif %}">
                        <p class="font-semibold" style="word-wrap: break-word;">{{ message.message }}</p>
                    </div>
                </div>
                <p class="text-xs text-gray-500 {% if message.sender == user %}text-right{% endif %}">{% if message.sender == user %}Me{% else %}{{ message.sender.username }}{% endif %}</p>
            {% endfor %}
        </div>
        <form id="msg-form" class="mt-4 flex gap-2">
            <textarea id="message" placeholder="Введите ваше сообщение" class="textarea textarea-bordered w-full"></textarea>
            <button type="submit" class="btn btn-primary">&#10003;</button>
        </form>
    {% else %}
        <h1 class="text-xl font-semibold text-center text-red-500">Доступ запрещен</h1>
        <button onclick="closeChat()" class="btn btn-sm btn-error">Закрыть</button>
    {% endif %}




{% endblock %}

templates/chat/chat_room.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Chat</title>
  <head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html {
      scroll-behavior: smooth;
    }

    .page-container {
      background-color: #b1b1b1;
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100%;
      height: 100vh;
    }

    .content {
      width: 80%;
      max-width: 500px;
      padding: 2rem;
      /* height: fit-content; */
      max-height: 80vh;
      background-color: #eef0f2;
      border-radius: 1rem;
      box-shadow: 0px 0px 1rem 0px rgba(0, 0, 0, 0.2);
      /* overflow-y: scroll; */

      display: grid;
      grid-template-rows: fit-content auto fit-content;
    }

    /* Hiding scrollbar for Chrome, Safari and Opera */
    .content::-webkit-scrollbar {
      display: none;
    }

    /* Hiding scrollbar for IE, Edge and Firefox */
    /* .content {
        scrollbar-width: none;
        -ms-overflow-style: none;
      } */

    h1 {
      text-align: center;
      font-size: 1.5rem;
      margin-bottom: 1rem;
    }

    input[type="text"] {
      outline: none;
      border: none;
      padding: 0.5rem 1rem;
      background-color: #dadee1;
      border-radius: 2rem;
      width: 100%;
      text-align: center;
    }

    button {
      /* margin-top: 1rem; */
      border: 0;
      outline: 0;
      padding: 0.5rem 0.75rem;
      background-color: #1b1f24;
      border-radius: 2rem;
      color: #ffffff;
      font-size: 1.25rem;
      font-weight: bold;
      transition: 0.25s ease;
      cursor: pointer;
    }

    button:hover {
      background-color: #353a41;
      /* justify-self: start; */
    }

    form {
      margin-top: 1rem;
      display: grid;
      grid-template-columns: auto 2.5rem;
      gap: 0.5rem;
    }

    textarea {
      height: 5rem;
      resize: none;
      outline: none;
      border: none;
      padding: 0.5rem 1rem;
      background-color: #dadee1;
      border-radius: 0.5rem;
      width: 100%;
      overflow-y: scroll;
    }

    /* Hiding scrollbar for Chrome, Safari and Opera */
    textarea::-webkit-scrollbar {
      display: none;
    }

    /* Hiding scrollbar for IE, Edge and Firefox */
    textarea {
      scrollbar-width: none;
      /* Firefox */
      -ms-overflow-style: none;
      /* IE and Edge */
    }

    .single-message {
      width: fit-content;
      max-width: 60%;
      clear: both;
    }

    .msg-body {
      margin-top: 0.25rem;
      padding: 0.5rem;
      background-color: #ff7300;
      color: #ffffff;
      font-size: 1rem;
      border-radius: 0.25rem;
      word-wrap: break-word;
    }

    .sent {
      float: right;
    }

    .sent>.msg-body {
      background-color: #8c00ff;
    }

    .sender {
      margin-top: 0.25rem;
      font-size: 0.75rem;
    }

    .chats-container {
      width: 100%;
      height: 20rem;
      overflow-y: scroll;
    }

    /* Hiding scrollbar for Chrome, Safari and Opera */
    .chats-container::-webkit-scrollbar {
      display: none;
    }

    /* Hiding scrollbar for IE, Edge and Firefox */
    .chats-container {
      scrollbar-width: none;
      /* Firefox */
      -ms-overflow-style: none;
      /* IE and Edge */
    }
  </style>
</head>

<body>
  <div class="page-container">
    <div class="content">
      {% if has_access %}
        <h1>Chat for Ticket #{{ ticket.id }}</h1>
        <div class="chats-container" id="chats-container">
          {% for message in messages %}
            {% if message.sender == user %}
              <div class="single-message sent">
                <div class="msg-body">{{ message.message }}</div>
                <p class="sender">Me</p>
              </div>
            {% else %}
              <div class="single-message">
                <div class="msg-body">{{ message.message }}</div>
                <p class="sender">{{ message.sender.username }}</p>
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <form id="msg-form">
          <textarea id="message" placeholder="Enter your message"></textarea>
          <button type="submit">&#10003;</button>
        </form>
      {% else %}
        <h1>Доступ запрещен</h1>
        <button onclick="closeChat()" class="btn btn-sm btn-error">Закрыть</button>
      {% endif %}
    </div>
  </div>

  {% if has_access %}
    <script>
      const socketURL = `ws://${window.location.host}/ws/chat/{{ ticket.id }}/`;
      const socket = new WebSocket(socketURL);

      document.getElementById("msg-form").addEventListener("submit", function (event) {
        event.preventDefault();
        let message_sent = document.getElementById("message").value;
        socket.send(JSON.stringify({ message: message_sent }));
      });

      const chats_div = document.getElementById("chats-container");

      socket.addEventListener("message", (e) => {
        const data = JSON.parse(e.data)["message"];
        let sender = data["sender"];
        let content = data["message"];

        if (sender == "{{ user.username }}") {
          chats_div.innerHTML += `<div class="single-message sent">
            <div class="msg-body">${content}</div>
            <p class="sender">Me</p>
          </div>`;
        } else {
          chats_div.innerHTML += `<div class="single-message">
            <div class="msg-body">${content}</div>
            <p class="sender">${sender}</p>
          </div>`;
        }
      });
    </script>
  {% endif %}
</body>
</html>

  <script>

    const socketURL = `ws://${window.location.host}/ws/chat/{{ ticket.id }}/`;
    console.log("Establishing Socket Connection")
    const socket = new WebSocket(socketURL)

    // Send Message to the backend
    const message_form = document.getElementById("msg-form")
    message_form.addEventListener("submit", function (event) {
      event.preventDefault();
      // console.log("Sending Message")
      let message_sent = document.getElementById("message").value;
      // console.log("Sending... ", message_sent);
      socket.send(JSON.stringify({ message: message_sent }));
    });

    const chats_div = document.getElementById("chats-container")

    // Scroll to bottom
    const scrollToBottom = () => {
      chats_div.scrollTop = chats_div.scrollHeight;
    }


    // Recieve Message from the backend
    socket.addEventListener("message", (e) => {
      const data = JSON.parse(e.data)["message"]

      console.log(data);

      let sender = data["sender"]
      let content = data["message"]

      if (sender == "{{user}}") {
        document.getElementById("message").value = ""
      }

      if (sender == "{{user}}") {
        document.getElementById("message").value = ""
      }



      if (sender == "{{user}}") {
        chats_div.innerHTML += `<div class="single-message sent">
          <div class="msg-body">${content}</div>
          <p class="sender">Me</p>
        </div>`;
      } else {
        chats_div.innerHTML += `<div class="single-message">
          <div class="msg-body">${content}</div>
          <p class="sender">${sender}</p>
        </div>`;
      }

      scrollToBottom();

    });
  </script>

templates/chat/get_chat_boss.html
{% load static %}
{% load tailwind_tags %}

{% block content4%}
<button type="button" onclick="closeChat()" class="absolute top-2 right-2 text-gray-500 hover:text-red-600 text-xl font-bold">&times;</button>
<h1 class="text-2xl font-bold text-center text-gray-800">Чат для задания #{{ chat.ticket.id }}</h1>
{% if messages %}
<div class="chats-container overflow-y-auto h-auto min-h-[500px] p-4 border rounded-lg bg-gray-50" id="chats-container">

    {% for message in messages %}
        <div class="flex {% if message.sender == first_sender %}justify-end{% else %}justify-start{% endif %}">
            <div class="max-w-xs px-4 py-2 rounded-lg {% if message.sender == first_sender %}bg-purple-600 text-white{% else %}bg-orange-500 text-white{% endif %}">
                <p class="font-semibold" style="word-wrap: break-word;">{{ message.message }}</p>
            </div>
        </div>
        <p class="text-xs text-gray-500 {% if message.sender == first_sender %}text-right{% endif %}">{% if message.sender == user %}Me{% else %}{{ message.sender.username }}{% endif %}</p>
    {% endfor %}
{% else %}
    <h2 class="text-2xl font-bold text-center text-gray-800">пустой</h2>
{% endif %}
</div>
{% endblock %}