chat/urls.py
from django.urls import path, re_path
from . import views

# create urls

urlpatterns = [
    path('<int:ticket_id>/', views.chat_detail, name='chat_detail'),
    path('boss/<int:chat_id>', views.get_chat_boss, name='get_chat_boss'),
    path('send_message/<int:chat_id>/', views.send_message, name='send_message'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
    path("__reload__/", include("django_browser_reload.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

tickets/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.ticket_list, name='ticket_list'),
    path('ticket_list_created_by', views.ticket_list_created_by, name='ticket_list_created_by'),
    path('ticket_list_accepted_by', views.ticket_list_accepted_by, name='ticket_list_accepted_by'),
    path('ticket_list_for_boss', views.ticket_list_for_boss, name='ticket_list_for_boss'),
    path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('accept_ticket/<int:ticket_id>/', views.accept_ticket, name='accept_ticket'),
    path('close_ticket/<int:ticket_id>/', views.close_ticket, name='close_ticket'),
    path('create/', views.create_ticket, name='create_ticket'),
    path('ticket/<int:ticket_id>/redirect/', views.redirect_ticket, name='redirect_ticket'),
    path('ticket/<int:ticket_id>/clone/', views.clone_ticket, name='clone_ticket'),
    path('ticket/data_analytics/',views.tickets_analytics_for_the_department,  name='data_analytics_for_the_department'),
]

tickets/forms.py
from django import forms
from .models import Ticket, Position

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['title', 'description', 'department', 'position', 'attachment']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # Вызов __init__ родительского класса
        self.fields['title'].required = True
        self.fields['department'].required = True
        self.fields['position'].required = True




class TicketRedirectForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['title', 'description', 'attachment', 'department', 'position']

    def __init__(self, *args, **kwargs):
        super(TicketRedirectForm, self).__init__(*args, **kwargs)
        # Запрещаем изменение title, description, attachment
        self.fields['title'].disabled = True
        self.fields['description'].disabled = True
        self.fields['attachment'].disabled = True

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['position'].queryset = Position.objects.filter(department_id=department_id)
            except (ValueError, TypeError):
                self.fields['position'].queryset = Position.objects.none()
        elif self.instance.pk:
            self.fields['position'].queryset = self.instance.department.positions.all()


class TicketCloneForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['title', 'description', 'attachment', 'department', 'position']

    def __init__(self, *args, **kwargs):
        super(TicketCloneForm, self).__init__(*args, **kwargs)
        # Запрещаем изменение title, description, attachment
        self.fields['title'].disabled = True
        self.fields['description'].disabled = True
        self.fields['attachment'].disabled = True

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['position'].queryset = Position.objects.filter(department_id=department_id)
                self.instance.id = None  # Сбрасываем ID при изменении отдела
            except (ValueError, TypeError):
                self.fields['position'].queryset = Position.objects.none()
        elif self.instance.pk:
            self.fields['position'].queryset = self.instance.department.positions.all()

tickets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from chat.models import Chat  # импорт модели чата
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from .models import Ticket
from .forms import TicketForm, TicketRedirectForm, TicketCloneForm
from account.models import CustomUser
from chat.models import Chat
from django.utils import timezone
from django.db.models import Q
from datetime import timedelta


from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


@login_required
def ticket_list(request):
    user = request.user
    chat_id = None
    tickets = Ticket.objects.filter(
        department=user.department,
        position=user.position
    )

    # Get the filter period from GET parameters (today, week, or month)
    time_filter = request.GET.get('time_filter', 'today')  # Default to 'today'

    # Filter tickets based on time period
    if time_filter == 'today':
        tickets = tickets.filter(created_at__date=timezone.now().date())
    elif time_filter == 'week':
        start_of_week = timezone.now() - timedelta(days=timezone.now().weekday())
        tickets = tickets.filter(created_at__gte=start_of_week)
    elif time_filter == 'month':
        tickets = tickets.filter(created_at__year=timezone.now().year,
                                 created_at__month=timezone.now().month)

    # Retrieve chat info
    chat = Chat.objects.filter(
        Q(ticket__accepted_by=user) | Q(ticket__created_by=user), is_active=True
    ).first()

    chat_id = chat.ticket.id if chat else None

    return render(request, 'tickets/ticket_list.html', {
        'tickets': tickets,
        'chat_id': chat_id
    })


@login_required
def ticket_list_created_by(request):
    user = request.user
    time_filter = request.GET.get('time_filter', 'today')  # Default to 'today'
    tickets = Ticket.objects.filter(created_by=request.user)

    if time_filter == 'today':
        tickets = tickets.filter(created_at__date=timezone.now().date())
    elif time_filter == 'week':
        start_of_week = timezone.now() - timedelta(days=timezone.now().weekday())
        tickets = tickets.filter(created_at__gte=start_of_week)
    elif time_filter == 'month':
        tickets = tickets.filter(created_at__year=timezone.now().year,
                                 created_at__month=timezone.now().month)

    chat = Chat.objects.filter(
        Q(ticket__accepted_by=user) | Q(ticket__created_by=user), is_active=True
    ).first()

    chat_id = chat.ticket.id if chat else None

    return render(request, 'tickets/my_created_ticket_list.html', {
        'tickets': tickets,
        'chat_id': chat_id
    })


@login_required
def ticket_list_accepted_by(request):
    user = request.user
    time_filter = request.GET.get('time_filter', 'today')  # Default to 'today'
    tickets = Ticket.objects.filter(accepted_by=request.user)

    if time_filter == 'today':
        tickets = tickets.filter(created_at__date=timezone.now().date())
    elif time_filter == 'week':
        start_of_week = timezone.now() - timedelta(days=timezone.now().weekday())
        tickets = tickets.filter(created_at__gte=start_of_week)
    elif time_filter == 'month':
        tickets = tickets.filter(created_at__year=timezone.now().year,
                                 created_at__month=timezone.now().month)

    chat = Chat.objects.filter(
        Q(ticket__accepted_by=user) | Q(ticket__created_by=user), is_active=True
    ).first()

    chat_id = chat.ticket.id if chat else None

    return render(request, 'tickets/my_accepted_ticket_list.html', {
        'tickets': tickets,
        'chat_id': chat_id
    })


@login_required
def ticket_list_for_boss(request):
    user = request.user
    chat_id = None
    tickets = Ticket.objects.filter(
        Q(status="closed") | Q(status="in_progress"),
        department=user.department
    )
    users = CustomUser.objects.filter(department=user.department).exclude(id=user.department.boss.id)

    # Get the filter period from GET parameters (today, week, or month)
    time_filter_user = request.GET.get('time_filter_user', 'today')  # Default to 'today'

    # Filter tickets based on time period
    if time_filter_user == 'today':
        tickets = tickets.filter(created_at__date=timezone.now().date())
    elif time_filter_user == 'week':
        start_of_week = timezone.now() - timedelta(days=timezone.now().weekday())
        tickets = tickets.filter(created_at__gte=start_of_week)
    elif time_filter_user == 'month':
        tickets = tickets.filter(created_at__year=timezone.now().year,
                                 created_at__month=timezone.now().month)

    specific_user = request.GET.get('specific_user', '')
    if specific_user:
        try:
            specific_user = int(specific_user)  # Convert to an integer
            tickets = tickets.filter(accepted_by=specific_user)
        except ValueError:
            pass  # If conversion fails, do nothing (avoid crashing)

    specific_status = request.GET.get('specific_status', '')
    if specific_status:
        tickets = tickets.filter(status=specific_status)

    # Retrieve chat info
    chat = Chat.objects.filter(
        Q(ticket__accepted_by=user) | Q(ticket__created_by=user), is_active=True
    ).first()

    chat_id = chat.ticket.id if chat else None

    return render(request, 'tickets/ticket_list_for_boss.html', {
        'tickets': tickets,
        'users': users,
        'chat_id': chat_id
    })


@login_required
def ticket_detail(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)

    return render(request, 'tickets/ticket_detail.html', {'ticket': ticket})

@login_required
def create_ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.created_by = request.user
            ticket.save()
            return redirect('tickets:ticket_list')
    else:
        form = TicketForm()
    return render(request, 'tickets/create_ticket.html', {'form': form})



@login_required
def accept_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)

    if ticket.status != 'open':
        messages.error(request, "Эта задача уже занята или завершена.")
        return redirect('tickets:ticket_list')

    if ticket.department != request.user.department or ticket.position != request.user.position or ticket.created_by == request.user:
        messages.error(request, "У вас нет прав на принятие этой задачи.")
        raise PermissionDenied("Вы не можете принять эту задачу.")

    # Назначаем задачу текущему пользователю и обновляем статус
    ticket.accepted_by = request.user
    ticket.accepted_at = timezone.now()
    ticket.status = 'in_progress'
    ticket.save()

    # Создаем чат для тикета, если его еще нет
    chat, created = Chat.objects.get_or_create(ticket=ticket)
    if created:
        chat.participants.add(ticket.created_by, request.user)
        chat.save()

    messages.success(request, "Задача успешно принята в работу!")
    return redirect('tickets:ticket_detail', ticket_id=ticket.id)

# tickets/views.py
@login_required
def close_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)

    # Здесь можно добавить проверки прав, например, только администратор или тот, кто принял задачу, может закрыть тикет
    if  ticket.status != 'in_progress':
        messages.error(request, "Эту задачу невозможно завершить, поскольку она либо не была принята в работу, либо уже завершена.")
        return redirect('tickets:ticket_list')

    if ticket.department != request.user.department or ticket.position != request.user.position or ticket.accepted_by != request.user:
        messages.error(request, "У вас нет прав на завершения этой задачи.")
        raise PermissionDenied("Вы не можете завершеть эту задачу.")

    if request.method == "POST":
        comment = request.POST.get("completion_comment")
        if not comment:
            messages.error(request, "Вы должны добавить комментарий перед закрытием задачи.")
            return redirect('tickets:ticket_detail', ticket_id=ticket.id)

    ticket.completion_comment = comment
    ticket.closed_at = timezone.now()
    ticket.status = 'closed'
    ticket.save()

    # Делаем чат неактивным, а не удаляем его
    if hasattr(ticket, 'chat'):
        ticket.chat.is_active = False
        ticket.chat.save()

        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            f"chat_{ticket.id}",
            {
                "type": "chat_closed",
                "ticket_id": ticket.id
            }
        )

    messages.success(request, "Задача успешно закрыта, чат удален.")
    return redirect('tickets:ticket_detail', ticket_id=ticket.id)



@login_required
def redirect_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)

    if ticket.status == 'in_progress' or ticket.status == 'closed':
        messages.error(request, "Тикет нельзя перенаправить, так как он в процессе выполнения или уже выполнен.")
        return redirect('tickets:ticket_list')

    if ticket.accepted_by == request.user or ticket.accepted_at is not None:
         messages.error(request, "Вы не можете перенаправить этот тикет, так как он уже был принят вами.")
         return redirect('tickets:ticket_list')

    if ticket.department != request.user.department or ticket.position != request.user.position:
        messages.error(request, "Вы не можете перенаправить этот тикет, так как он предназначен не для вашего отдела или позиции .")
        return redirect('tickets:ticket_list')

    if request.method == 'POST':
        ticket.old_position = ticket.position
        ticket.old_department = ticket.department

templates/tickets/clone_ticket.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container mx-auto p-6 flex justify-center">
    <div class="card bg-base-100 shadow-xl border border-gray-200 p-6 w-full max-w-lg">
        <h2 class="text-3xl font-bold mb-4 text-center">Клонировать задачу</h2>
        <form method="post" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Отдел</span>
                </label>
                {{ form.department }}
            </div>
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Должность</span>
                </label>
                {{ form.position }}
            </div>
<!--            <div class="form-control">-->
<!--                <label class="label">-->
<!--                    <span class="label-text">Due Date</span>-->
<!--                </label>-->
<!--                {{ form.due_date }}-->
<!--            </div>-->
            <div class="flex justify-center">
                <button type="submit" class="btn btn-primary w-full">Клонировать</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/tickets/create_ticket.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container mx-auto p-6 flex justify-center">
    <div class="card bg-base-100 shadow-xl border border-gray-200 p-6 w-full max-w-lg">
        <h2 class="text-3xl font-bold mb-4 text-center">Создать задачу</h2>
        <form method="post" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Заголовок</span>
                </label>
                {{ form.title }}
            </div>
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Описание</span>
                </label>
                {{ form.description }}
            </div>
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Отдел</span>
                </label>
                {{ form.department }}
            </div>
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Должность</span>
                </label>
                {{ form.position }}
            </div>
<!--            <div class="form-control">-->
<!--                <label class="label">-->
<!--                    <span class="label-text">Due Date</span>-->
<!--                </label>-->
<!--                {{ form.due_date }}-->
<!--            </div>-->
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Прикрепить файл (скриншот или PDF)</span>
                </label>
            {{ form.attachment }}
            </div>
            <div class="flex justify-center">
                <button type="submit" class="btn btn-primary w-full">Отправить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/tickets/redirect_ticket.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container mx-auto p-6 flex justify-center">
    <div class="card bg-base-100 shadow-xl border border-gray-200 p-6 w-full max-w-lg">
        <h2 class="text-3xl font-bold mb-4 text-center">Перенаправить задачу</h2>
        <form method="post" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Отдел</span>
                </label>
                {{ form.department }}
            </div>
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Должность</span>
                </label>
                {{ form.position }}
            </div>
<!--            <div class="form-control">-->
<!--                <label class="label">-->
<!--                    <span class="label-text">Due Date</span>-->
<!--                </label>-->
<!--                {{ form.due_date }}-->
<!--            </div>-->
            <div class="flex justify-center">
                <button type="submit" class="btn btn-primary w-full">Перенаправить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/tickets/ticket_detail.html
{% extends "blog/base.html" %}
{% block content2 %}
{% load l10n %}
<div class="container mx-auto p-6">
    <div class="card bg-base-100 shadow-xl border border-gray-200 p-6">
        <h1 class="text-3xl font-bold mb-2">Задания №{{ ticket.id }}</h1>
        <h2 class="text-3xl font-bold mb-2">{{ ticket.title }}</h2>
        <p class="text-gray-600">{{ ticket.description }}</p>
        
        <div class="mt-4">
            <p>Статус:
                    <span class="badge
                        {% if ticket.status == 'open' %}badge-error
                        {% elif ticket.status == 'in_progress' %}badge-warning
                        {% else %}badge-success
                        {% endif %}">
                        {% if ticket.status == 'open' %}Открыт
                        {% elif ticket.status == 'in_progress' %}В процессе
                        {% else %}Закрыт
                        {% endif %}
                    </span>
                </p>
            <p>
                <strong>Задача была создана:</strong>
                {% if ticket.created_by.first_name and ticket.created_by.last_name and ticket.created_by.position%}
                    {{ ticket.created_by.first_name }}
                    {{ ticket.created_by.last_name }}
                    {{ ticket.created_by.position }}
                {% else %}
                    {{ ticket.created_by.username }}
                    {{ ticket.created_by.position }}
                {% endif %} в
                {{ ticket.created_at }}
                {% if ticket.created_by.profile.number %}
                    внутренний номер: {{ ticket.created_by.profile.number }}
                {% else %}
                    {{ ticket.created_by.profile.number|default:"У пользователя нету внутреннего номера" }}
                {% endif %}

            <p><strong>Задача была принята:</strong>
                {% if ticket.accepted_by %}
                    {% if ticket.accepted_by.first_name and ticket.created_by.last_name and ticket.accepted_by.position%}
                        {{ ticket.accepted_by.first_name }}
                        {{ ticket.accepted_by.last_name }}
                        {{ ticket.accepted_by.position }} в
                        {{ ticket.accepted_at }}
                    {% else %}
                        {{ ticket.accepted_by.username }}
                        {{ ticket.accepted_by.position }}
                    {% endif %}
                {% else %}
                {{ ticket.accepted_by.username|default:"На данный момент не принята" }}
                {% endif %}
                {% if ticket.accepted_by.profile.number %}
                    внутренний номер: {{ ticket.accepted_by.profile.number }}
                {% endif %}
                {% if ticket.closed_at %}
                    <p><strong>Задача была закрыта:</strong>
                     {% if ticket.accepted_by.first_name and ticket.created_by.last_name and ticket.accepted_by.position%}
                        {{ ticket.accepted_by.first_name }}
                        {{ ticket.accepted_by.last_name }}
                        {{ ticket.accepted_by.position }} в
                        {{ ticket.closed_at }}
                    {% else %}
                        {{ ticket.accepted_by.username }}
                        {{ ticket.accepted_by.position }}
                    {% endif %}
                {% endif %}
            </p>
        </div>

        {% if ticket.attachment %}
        <div class="mt-4">
            <h3 class="text-lg font-semibold">Прикрепленный файл:</h3>
            <div class="border border-gray-300 rounded-lg overflow-hidden shadow-md max-w-xs">
                {% with ticket.attachment.name|lower as filename %}
                    {% with filename|slice:"-4:" as ext %} {# берём последние 4 символа, например .jpg #}
                        {% if ext in ".jpg,.png,.gif,.jpeg" %}
                            <!-- Для изображений -->
                            <img src="{{ ticket.attachment.url }}" alt="Прикрепленный файл" class="w-full h-auto">
                            <div class="p-2 bg-gray-100 text-center">
                                <a href="{{ ticket.attachment.url }}" target="_blank" class="link link-primary">Открыть изображение</a>
                            </div>
                        {% elif ext == ".pdf" %}
                            <!-- Для PDF -->
                            <div class="flex items-center justify-center p-4 bg-gray-50">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-red-500" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM8 17H6v-2h2v2zm0-4H6v-2h2v2zm0-4H6V7h2v2zm10 8h-8v-2h8v2zm0-4h-8v-2h8v2zm0-4h-8V7h8v2z"/>
                                </svg>
                            </div>
                            <div class="p-2 bg-gray-100 text-center">
                                <a href="{{ ticket.attachment.url }}" target="_blank" class="link link-primary">Открыть PDF</a>
                            </div>
                        {% else %}
                            <!-- Для всех остальных файлов -->
                            <div class="flex items-center justify-center p-4 bg-gray-50">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-gray-500" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M14 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V8l-6-6zM13 9V3.5L18.5 9H13z"/>
                                </svg>
                            </div>
                            <div class="p-2 bg-gray-100 text-center">
                                <a href="{{ ticket.attachment.url }}" target="_blank" class="link link-primary">Скачать файл</a>
                            </div>
                        {% endif %}
                    {% endwith %}
                {% endwith %}
            </div>
        </div>
    {% endif %}
    {% if ticket.status == 'open' %}
        {% if ticket.status != 'in_progress' and ticket.status != 'closed' and ticket.accepted_by is None and ticket.accepted_at is None and ticket.department == request.user.department and ticket.position == request.user.position %}
            <div class="fixed bottom-4 right-4">
                <a href="{% url 'tickets:redirect_ticket' ticket.id %}" class="btn btn-primary shadow-lg">
                    🔄 Перенаправить тикет
                </a>
            </div>
        {% endif %}
     {% endif %}
     {% if ticket.status == 'in_progress' %}
        {% if ticket.status != 'open' and ticket.status != 'closed' and ticket.accepted_by is not None and ticket.accepted_at is not None and ticket.department == request.user.department and ticket.position == request.user.position %}
            <div class="fixed bottom-4 right-4">
                <a href="{% url 'tickets:clone_ticket' ticket.id %}" class="btn bg-lime-500 text-white shadow-lg">
                    ➕ Клонировать тикет
                </a>
            </div>
        {% endif %}
     {% endif %}
        <div class="mt-6">
            {% if ticket.status == 'open' %}
                {% if ticket.department == request.user.department and ticket.position == request.user.position and ticket.created_by != request.user%}
                <form action="{% url 'tickets:accept_ticket' ticket.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Принять задание</button>
                </form>
                {% else %}
                    <!--<p class="text-gray-500">you don't have access rights to accept ticket.</p>-->
                {% endif %}
            {% elif ticket.status == 'in_progress' %}
                {% if ticket.department == request.user.department and ticket.position == request.user.position and ticket.accepted_by == request.user %}
                    <form action="{% url 'tickets:close_ticket' ticket.id %}" method="post" class="mt-3 p-3 border rounded bg-light shadow-sm">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="completion_comment" class="form-label fw-bold">Комментарий перед закрытием:</label>
                            <textarea name="completion_comment" id="completion_comment" class="form-control" rows="5" style="width: 100%;" placeholder="Опишите, что было сделано..." required></textarea>
                        </div>
                        <button type="submit" class="btn btn-success w-100 fw-bold">Закрыть задание</button>
                    </form>
                {% endif %}
            {% else %}
                <div class="mb-3">
                <label class="form-label fw-bold">Комментарий:</label>
                <div class="p-2 border rounded bg-white" style="word-wrap: break-word;">
                    {{ ticket.completion_comment }}
                </div>
            </div>


            {% endif %}
        </div>
    </div>
</div>
{% endblock %}